name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run test:coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1

  # release:
  #   if: github.ref == 'refs/heads/master'
  #   needs: test

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - run: npm ci
  #     - run: npx semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
